AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*
    - vendor/**/*
    - Gemfile

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/GuardClause:
  MinBodyLength: 5

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Naming/MethodName:
  Exclude:
    - lib/core_ext/**/*

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/serializers/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Exclude:
    - lib/core_ext/**/*

Metrics/AbcSize:
  Exclude:
    - app/queries/**/*

Rails/InverseOf:
  Enabled: false
